services:
  db:
    image: mariadb:10.11
    container_name: seafile-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # อ้างจาก .env
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql  # อ้างจาก .env
    networks:
      - seafile-net

  memcached:
    image: memcached:1.6.18
    container_name: seafile-memcached
    restart: always
    entrypoint: memcached -m 256
    networks:
      - seafile-net
          
  seafile:
    image: seafileltd/seafile-mc:11.0-latest
    container_name: seafile
    restart: always
    ports:
      - "${SEAFILE_PORT}:80"  # อ้างจาก .env
      # - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - ${SEAFILE_DATA_DIR}:/shared  # อ้างจาก .env
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=${MYSQL_ROOT_PASSWORD}  # อ้างจาก .env
      - TIME_ZONE=${TIME_ZONE}  # อ้างจาก .env
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL}  # อ้างจาก .env
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}  # อ้างจาก .env
      - SEAFILE_SERVER_LETSENCRYPT=${SEAFILE_SERVER_LETSENCRYPT}  # อ้างจาก .env
      - SEAFILE_SERVER_HOSTNAME=${SEAFILE_SERVER_HOSTNAME}  # อ้างจาก .env
      #- HTTPS=true  # If https is enabled, cancel the comment.

    depends_on:
      - db
      - memcached
    networks:
      - seafile-net

networks:
  seafile-net: