version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-auth
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]