services:
  vault:
    platform: linux/amd64
    image: hashicorp/vault:latest
    container_name: vault
    restart: unless-stopped
    ports:
      - "8201:8201"
    volumes:
      - vault-data:/vault/data
      - vault-logs:/vault/logs
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8201
      VAULT_ADDR: http://0.0.0.0:8201
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Vault UI สำหรับทีม
  vault-ui:
    platform: linux/amd64
    image: djenriquez/vault-ui:latest
    container_name: vault-ui
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # ใช้ host.docker.internal แทน vault service name
      VAULT_URL_DEFAULT: http://host.docker.internal:8201
      VAULT_AUTH_DEFAULT: USERPASS
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    depends_on:
      - vault
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  vault-data:
    driver: local
  vault-logs:
    driver: local